version: '3'

services:
  splunk-main:
    image: splunk/splunk:latest
    platform: linux/amd64
    ports:
      - "8000:8000"
      - "8089:8089"
      - "8088:8088"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Uvish123@
      - OPTIMISTIC_ABOUT_FILE_LOCKING=1
    volumes:
      - splunk-var:/opt/splunk/var
      - splunk-etc:/opt/splunk/etc

  splunk-US:
    image: splunk/splunk:latest
    platform: linux/amd64
    ports:
      - "1000:8000"
      - "1089:8089"
      - "1088:8088"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Uvish123@
      - OPTIMISTIC_ABOUT_FILE_LOCKING=1
    volumes:
      - splunk-var-us:/opt/splunk/var
      - splunk-etc-us:/opt/splunk/etc

  splunk-EMEA:
    image: splunk/splunk:latest
    platform: linux/amd64
    ports:
      - "2000:8000"
      - "2089:8089"
      - "2088:8088"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Uvish123@
      - OPTIMISTIC_ABOUT_FILE_LOCKING=1
    volumes:
      - splunk-var-emea:/opt/splunk/var
      - splunk-etc-emea:/opt/splunk/etc

  splunk-APAC:
    image: splunk/splunk:latest
    platform: linux/amd64
    ports:
      - "3000:8000"
      - "3089:8089"
      - "3088:8088"
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=Uvish123@
      - OPTIMISTIC_ABOUT_FILE_LOCKING=1
    volumes:
      - splunk-var-apac:/opt/splunk/var
      - splunk-etc-apac:/opt/splunk/etc


  enumerator:
    build:
      context: ./splunk_enumerator
    container_name: enumerator
    depends_on:
      - splunk-US
      - splunk-EMEA
      - splunk-APAC
      - splunk-main
    environment:
      - DOCKER_CONTAINER=true
    healthcheck:
      test: ["CMD","curl", "--fail" ,"http://localhost:1111/ping || exit 1"]
      interval: 5s
      timeout: 2s
      retries: 10
    restart: on-failure
    stop_signal: SIGKILL


  backend:
    build:
      context: ./data_dictionary_backend
    container_name: backend
    depends_on:
      - splunk-main
    ports:
      - "3333:3333" 
    environment:
      - DOCKER_CONTAINER=true


  frontend:
    build:
      context: ./data_dictionary_frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:8080" 
    environment:
      - DOCKER_CONTAINER=true
  

volumes:
  splunk-var:
  splunk-etc:
  splunk-var-us:
  splunk-etc-us:
  splunk-var-emea:
  splunk-etc-emea:
  splunk-var-apac:
  splunk-etc-apac:
