name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn --cwd data_dictionary_frontend/packages/datadictionary install
    - run: yarn --cwd data_dictionary_frontend/packages/datadictionary build
    - run: yarn --cwd data_dictionary_backend install
    - run: yarn --cwd data_dictionary_backend lint
    - run: yarn --cwd splunk_enumerator install
    - run: yarn --cwd splunk_enumerator lint
